export const DOCUMENT_VIEW_DENIED = "DOCUMENT_VIEW_DENIED";
export const DOCUMENT_EDIT_DENIED = "DOCUMENT_EDIT_DENIED";
export const DOCUMENT_UPDATE_DENIED = "DOCUMENT_UPDATE_DENIED";
export const DOCUMENT_CREATE_DENIED = "DOCUMENT_CREATE_DENIED";

export const DOCUMENT_CREATED = "DOCUMENT_CREATED";
export const DOCUMENT_UPDATED = "DOCUMENT_UPDATED";
export const DOCUMENT_VIEWED = "DOCUMENT_VIEWED";

export const DOCUMENT_SUBMITTED_FOR_APPROVAL = "DOCUMENT_SUBMITTED_FOR_APPROVAL";
export const DOCUMENT_SUBMIT_DENIED = "DOCUMENT_SUBMIT_DENIED";
export const DOCUMENT_APPROVED = "DOCUMENT_APPROVED";
export const DOCUMENT_REJECTED = "DOCUMENT_REJECTED";
export const DOCUMENT_RETURNED_FOR_REVISION = "DOCUMENT_RETURNED_FOR_REVISION";
export const APPROVAL_DECISION_DENIED = "APPROVAL_DECISION_DENIED";
export const DOCUMENT_ARCHIVED = "DOCUMENT_ARCHIVED";
export const DOCUMENT_ARCHIVE_DENIED = "DOCUMENT_ARCHIVE_DENIED";

export const MFA_ENABLED = "MFA_ENABLED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
