export const DOCUMENT_SIGNED = "DOCUMENT_SIGNED";
export const DOCUMENT_SIGN_DENIED = "DOCUMENT_SIGN_DENIED";
export const DOCUMENT_SIGNATURE_VERIFIED = "DOCUMENT_SIGNATURE_VERIFIED";
export const DOCUMENT_SIGNATURE_INVALID = "DOCUMENT_SIGNATURE_INVALID";
export const CERTIFICATE_GENERATED = "CERTIFICATE_GENERATED";
